In [1]:
import pandas as pd

df = pd.read_csv("nba-2.csv")

df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,2-Jun,180,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,6-Jun,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,5-Jun,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,5-Jun,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,10-Jun,231,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,20,10-Jun,234,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8,PG,26,3-Jun,203,Butler,2433333.0
454,Raul Neto,Utah Jazz,25,PG,24,1-Jun,179,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21,C,26,3-Jul,256,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24,C,26,Jul-00,231,Kansas,947276.0

In [10]:
first = df.groupby('Team')
first.last()  # .first() && .last()

,Name,Number,Position,Age,Height,Weight,College,Salary
Team,,,,,,,,
Atlanta Hawks,Jeff Teague,0,PG,27,2-Jun,186,Wake Forest,8000000.0
Boston Celtics,Tyler Zeller,44,C,26,Jul-00,253,North Carolina,2616975.0
Brooklyn Nets,Thaddeus Young,30,PF,27,8-Jun,221,Georgia Tech,11235955.0
Charlotte Hornets,Cody Zeller,40,C,23,Jul-00,240,Indiana,4204200.0
Chicago Bulls,Tony Snell,20,SF,24,7-Jun,200,New Mexico,1535880.0
Cleveland Cavaliers,Mo Williams,52,PG,33,1-Jun,198,Alabama,2100000.0
Dallas Mavericks,Deron Williams,8,PG,31,3-Jun,200,Illinois,5378974.0
Denver Nuggets,Axel Toupane,6,SG,23,7-Jun,210,St. John's,258489.0
Detroit Pistons,Anthony Tolliver,43,PF,31,8-Jun,240,Creighton,3000000.0
Golden State Warriors,Anderson Varejao,18,PF,33,11-Jun,273,Washington State,289755.0
Houston Rockets,Jason Terry,31,SG,38,2-Jun,185,Arizona,947276.0
Indiana Pacers,Joe Young,1,PG,23,2-Jun,180,Oregon,1007026.0
Los Angeles Clippers,C.J. Wilcox,30,SG,25,5-Jun,195,Washington,1159680.0
Los Angeles Lakers,Nick Young,0,SF,31,7-Jun,210,USC,5219169.0
Memphis Grizzlies,Brandan Wright,34,PF,28,10-Jun,210,North Carolina,5464000.0
Miami Heat,Dorell Wright,11,SF,30,9-Jun,205,Duke,2481720.0
Milwaukee Bucks,Rashad Vaughn,20,SG,19,6-Jun,202,UNLV,1733040.0
Minnesota Timberwolves,Andrew Wiggins,22,SG,21,8-Jun,199,Kansas,5758680.0
New Orleans Pelicans,Quincy Pondexter,20,SF,28,7-Jun,220,Washington,3382023.0
New York Knicks,Tony Wroten,5,SG,23,6-Jun,205,Washington,167406.0
Oklahoma City Thunder,Russell Westbrook,0,PG,27,3-Jun,200,UCLA,16744218.0
Orlando Magic,C.J. Watson,32,PG,32,2-Jun,175,Tennessee,5000000.0
Philadelphia 76ers,Christian Wood,35,PF,20,11-Jun,220,UNLV,525093.0
Phoenix Suns,Alan Williams,15,C,23,8-Jun,260,UC Santa Barbara,83397.0
Portland Trail Blazers,Noah Vonleh,21,PF,20,9-Jun,240,Indiana,2637720.0
Sacramento Kings,Rajon Rondo,9,PG,30,1-Jun,186,Kentucky,9500000.0
San Antonio Spurs,David West,30,PF,35,9-Jun,250,Xavier,1499187.0
Toronto Raptors,Delon Wright,55,PG,24,5-Jun,190,Utah,1509360.0
Utah Jazz,Jeff Withey,24,C,26,Jul-00,231,Kansas,947276.0
Washington Wizards,John Wall,2,PG,25,4-Jun,195,Kentucky,15851950.0

In [8]:
first.get_group('Golden State Warriors')

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
76,Leandro Barbosa,Golden State Warriors,19,SG,33,3-Jun,194,NaN,2500000.0
77,Harrison Barnes,Golden State Warriors,40,SF,24,8-Jun,225,North Carolina,3873398.0
78,Andrew Bogut,Golden State Warriors,12,C,31,Jul-00,260,Utah,13800000.0
79,Ian Clark,Golden State Warriors,21,SG,25,3-Jun,175,Belmont,947276.0
80,Stephen Curry,Golden State Warriors,30,PG,28,3-Jun,190,Davidson,11370786.0
81,Festus Ezeli,Golden State Warriors,31,C,26,11-Jun,265,Vanderbilt,2008748.0
82,Draymond Green,Golden State Warriors,23,PF,26,7-Jun,230,Michigan State,14260870.0
83,Andre Iguodala,Golden State Warriors,9,SF,32,6-Jun,215,Arizona,11710456.0
84,Shaun Livingston,Golden State Warriors,34,PG,30,7-Jun,192,NaN,5543725.0
85,Kevon Looney,Golden State Warriors,36,SF,20,9-Jun,220,UCLA,1131960.0
86,James Michael McAdoo,Golden State Warriors,20,SF,23,9-Jun,240,North Carolina,845059.0
87,Brandon Rush,Golden State Warriors,4,SF,30,6-Jun,220,Kansas,1270964.0
88,Marreese Speights,Golden State Warriors,5,C,28,10-Jun,255,Florida,3815000.0
89,Klay Thompson,Golden State Warriors,11,SG,26,7-Jun,215,Washington State,15501000.0
90,Anderson Varejao,Golden State Warriors,18,PF,33,11-Jun,273,NaN,289755.0

In [16]:
second = df.groupby(['Age','Position','Team'])
second.last()

                                                   Name  Number  Height  \
Age Position Team
19  SG       Milwaukee Bucks              Rashad Vaughn      20   6-Jun
             Phoenix Suns                  Devin Booker       1   6-Jun
20  C        Minnesota Timberwolves  Karl-Anthony Towns      32  Jul-00
             Philadelphia 76ers           Jahlil Okafor       8  11-Jun
    PF       Indiana Pacers                Myles Turner      33  11-Jun
...                                                 ...     ...     ...
39  PG       Los Angeles Clippers        Pablo Prigioni       9   3-Jun
    SG       Memphis Grizzlies             Vince Carter      15   6-Jun
40  C        San Antonio Spurs               Tim Duncan      21  11-Jun
    PF       Minnesota Timberwolves       Kevin Garnett      21  11-Jun
    PG       San Antonio Spurs             Andre Miller      24   3-Jun

                                     Weight         College     Salary
Age Position Team
19  SG       Milwaukee Bucks            202            UNLV  1733040.0
             Phoenix Suns               206        Kentucky  2127840.0
20  C        Minnesota Timberwolves     244        Kentucky  5703600.0
             Philadelphia 76ers         275            Duke  4582680.0
    PF       Indiana Pacers             243           Texas  2357760.0
...                                     ...             ...        ...
39  PG       Los Angeles Clippers       185            None   947726.0
    SG       Memphis Grizzlies          220  North Carolina  4088019.0
40  C        San Antonio Spurs          250     Wake Forest  5250000.0
    PF       Minnesota Timberwolves     240            None  8500000.0
    PG       San Antonio Spurs          200            Utah   250750.0

[413 rows x 6 columns]